yoloConf:
  model: '../models/base.pt'
  calibration_file: '../data/calibration_files/test_calibration.npy'
  vignetting_map: '../data/calibration_files/test_map.pkl'
  png_dir: '../data/benchmark/pngs'
  downsample_path: '../data/benchmark/downsampled_images'
  outpath: '../data/benchmark/yolo_outfiles'
  delete_yolo_output: True #Usually you want False unless you're benchmarking
  png_threshold: 1.4
  png_saturation: 4
  migdal_cut: 'NR_energy > 60 & centroid_dist < 6'
  GPU: True #set to True if using GPU else False
  
downsample:
  dark_file: '../data/dark/sample_master_dark.npy'
  data_dir: '../data/benchmark/random_benchmark_image' #input data directory
  batch_size: 1 #Size of batches for downsampling
  num_workers: 3 #number of parallel jobs for batch loading in downsample.py
  outpath: '../data/benchmark/downsampled_images' #outpath for downsampled images
  GPU: True #set to True if using GPU else False
  png_dir: '../data/benchmark/pngs'