yoloConf:
  model: '../models/base.pt'
  calibration_file: '../data/calibration_files/test_calibration.npy'
  vignetting_map: '../data/calibration_files/test_map.pkl'
  downsample_path: '../data/downsampled_images'
  outpath: '../data/yolo_outfiles'
  png_threshold: 1.4
  png_saturation: 4
  migdal_cut: 'NR_energy > 60 & centroid_dist < 6'
  
downsample:
  dark_file: '../data/dark/sample_master_dark.npy'
  data_dir: '../data/image_for_benchmark' #input data directory
  batch_size: 1 #Size of batches for downsampling
  num_workers: 2 #number of parallel jobs for batch loading in downsample.py
  outpath: '../data/downsampled_images' #outpath for downsampled images
